version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/workspace
    environment:
      PYTORCH_INDEX_URL_CU128: https://download.pytorch.org/whl/cu128
    runtime: nvidia
