name: build-keyframe-seeker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'cu128'
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'requirements.in'
      - 'constraints-base.txt'
      - 'runtime-pins.txt'
      - '.github/workflows/build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: casboko/keyframe-seeker/keyframe-seeker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_TAG: ${{ github.event.inputs.tag || 'cu128' }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 256
          swap-size-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true

      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check antlr dependency tree
        run: |
          set -euo pipefail
          python -m venv .venv-deptree
          source .venv-deptree/bin/activate
          python -m pip install --upgrade pip
          pip install pipdeptree
          pip install -c constraints-base.txt -r requirements-base.in
          pipdeptree -r -p antlr4-python3-runtime
          deactivate
          rm -rf .venv-deptree

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            PYTORCH_INDEX_URL_CU128=https://download.pytorch.org/whl/cu128
          cache-from: type=gha
          cache-to: type=gha,mode=max
